### ISSUE TITLE
Testing checklist

### ISSUE THREAD

**Issue by dhopp1** [dhopp1/COVID-19-status-reports#18]
- [x] change date range
- [x] change both countries
- [x] change x axis type + dates
- [x] change metric + x axis, check all tabs
- [x] change days moving average
- [x] check hover text
- [x] check copy
- [x] data sanity check with original CSSE files
- [x] data sanity check with RKI data
- [x] data sanity check overview table
